networks:
  challenge-network:
    driver: bridge

services:
  note-app:
    build: ./note-app
    networks:
      - challenge-network

  free-xss:
    build: ./free-xss
    networks:
      - challenge-network

  adminbot:
    build: ./adminbot
    environment:
      - FLAG=kalmar{test_flag}
      - XSS_DOMAIN=https://xss-spukhafte.kalmarctf.local/
      - NOTES_DOMAIN=https://notes-spukhafte.kalmarctf.local/
    networks:
      - challenge-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "443:443"
    depends_on:
      - note-app
      - free-xss
      - adminbot
    networks:
      challenge-network:
        aliases:
          - notes-spukhafte.kalmarctf.local
          - bot-spukhafte.kalmarctf.local
          - xss-spukhafte.kalmarctf.local
